spring:
  application:
    name: kalah-game
  datasource:
    url: jdbc:h2:mem:kalah-game;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
    
logging:
  file:
    name: logs/kalah-game.log

server:
  port: 8080 
  
swagger:
  title: Kalah Game API
  description: Kalah Game API documentation
  contact-email: avanish.k.pandey@gmail.com
  contact-name: Avanish